MicroIMDBV2/Models/Model.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MicroIMDBV2.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Year { get; set; }
    }

    public class Actor
    {
        public int Id { get; set; }
        public string ActorName { get; set; }
        public string ShortBio { get; set; }
    }

    public class Role 
    { 
        public int Id { get; set; }
        public string RoleName { get; set; }
        public virtual Movie movie { get; set; }
        public virtual Actor actor { get; set; }
    }
}

MicroIMDBV2/Models/MovieDBContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace MicroIMDBV2.Models
{
    public class MovieDBContext : DbContext
    {
        public DbSet<Movie> Movies { get; set; }
        public DbSet<Actor> Actores { get; set; }
        public DbSet<Role> Roles { get; set; }
    }
}

MicroIMDBV2/Controllers/MovieController.cs
using MicroIMDBV2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MicroIMDBV2.Controllers
{
    public class MovieController : Controller
    {
        // GET: Movie
        public ActionResult Index()
        {
            using (var db = new MovieDBContext())
            {
                var movies = db.Movies.ToList();
                return View(movies);
            }
        }
        [HttpPost]
        public ActionResult Add(Movie movieFromView)
        {
            using (var db = new MovieDBContext())
            {
                db.Movies.Add(movieFromView);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

MicroIMDBV2/Views/Movie/Add.cshtml
@model MicroIMDBV2.Models.Movie

@{ 
    ViewBag.Title = "Add";
}

@using (Html.BeginForm("Add", "Movie", FormMethod.Post, new { @class = "form-horizontal"}))
{
    <h2>Add Movie</h2>
    <div class="form-group">
        @Html.LabelFor(m => m.Title, new { @class = "col-md-2 control-label"})
        <div class="col-md-10"> @Html.TextBoxFor(m => m.Title, new { @class = "form-control" })</div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Year, new { @class = "col-md-2 control-label"})
        <div class="col-md-10"> @Html.TextBoxFor( m => m.Year, new { @class = "form-control" }) </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10"> <input type="submit" class="btn btn-default" value="Add Movie" /></div>
    </div>
}

MicroIMDBV2/Views/Movie/Index.cshtml
@model IEnumerable<MicroIMDBV2.Models.Movie>

@{ 
    ViewBag.Title = "Index";
}

@foreach(var movie in Model)
{
    @movie.Title <br/>
}

MicroIMDBV2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MicroIMDBv2", "Index", "Movie", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>